# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- unita*

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'ROWM.sln'
  myProject: "ROWM/ROWM.csprog"
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

resources:
  pipelines:
    - pipeline: hdrgis.row-services-base
      source: hdrgis.burr-row-manager
      trigger:
        branches:
          include:
            - master
                 
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '42c00845-cefc-4c11-9fb2-3103516553eb'
    definition: '9'
    buildVersionToDownload: 'latest'
    itemPattern: '*.js'
    targetPath: '$(Build.SourcesDirectory)\ROWM\wwwroot\js'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '42c00845-cefc-4c11-9fb2-3103516553eb'
    definition: '9'
    buildVersionToDownload: 'latest'
    itemPattern: '*.css'
    targetPath: '$(Build.SourcesDirectory)\ROWM\wwwroot\css'

- task: VSBuild@1
  inputs:
    solution: '$(myProject)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'