// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Negotiation_History", Schema = "SH72")]
    public partial class NegotiationHistory
    {
        public NegotiationHistory()
        {
            NegotiationContacts = new HashSet<NegotiationContact>();
            NegotiationDocuments = new HashSet<NegotiationDocument>();
            NegotiationParcels = new HashSet<NegotiationParcel>();
        }

        [Key]
        public Guid NegotiationId { get; set; }
        [Column("Contact_Date")]
        public DateTimeOffset ContactDate { get; set; }
        [Column("Offer_Amount", TypeName = "money")]
        public decimal? OfferAmount { get; set; }
        [Column("CounterOffer_Amount", TypeName = "money")]
        public decimal? CounterOfferAmount { get; set; }
        public bool? IsOffer { get; set; }
        public Guid OwnerId { get; set; }
        public Guid? ContactId { get; set; }
        [Column("Contact_Person_Name")]
        [StringLength(100)]
        public string ContactPersonName { get; set; }
        [Column("Contact_Number")]
        [StringLength(50)]
        public string ContactNumber { get; set; }
        [Column("Contact_Method")]
        [StringLength(50)]
        public string ContactMethod { get; set; }
        public Guid? NegotiatorId { get; set; }
        [Required]
        [Column("Negotator_Name")]
        [StringLength(100)]
        public string NegotatorName { get; set; }
        public string Notes { get; set; }
        public string Action { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [Required]
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ContactId))]
        [InverseProperty(nameof(ContactInfo.NegotiationHistories))]
        public virtual ContactInfo Contact { get; set; }
        [ForeignKey(nameof(NegotiatorId))]
        [InverseProperty(nameof(Agent.NegotiationHistories))]
        public virtual Agent Negotiator { get; set; }
        [ForeignKey(nameof(OwnerId))]
        [InverseProperty("NegotiationHistories")]
        public virtual Owner Owner { get; set; }
        [InverseProperty(nameof(NegotiationContact.Negotiation))]
        public virtual ICollection<NegotiationContact> NegotiationContacts { get; set; }
        [InverseProperty(nameof(NegotiationDocument.Negotiation))]
        public virtual ICollection<NegotiationDocument> NegotiationDocuments { get; set; }
        [InverseProperty(nameof(NegotiationParcel.Negotiation))]
        public virtual ICollection<NegotiationParcel> NegotiationParcels { get; set; }
    }
}