// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("NegotiationParcels", Schema = "SH72")]
    public partial class NegotiationParcel
    {
        [Key]
        public Guid NegotiationParcelId { get; set; }
        public Guid NegotiationId { get; set; }
        public Guid ParcelId { get; set; }

        [ForeignKey(nameof(NegotiationId))]
        [InverseProperty(nameof(NegotiationHistory.NegotiationParcels))]
        public virtual NegotiationHistory Negotiation { get; set; }
        [ForeignKey(nameof(ParcelId))]
        [InverseProperty("NegotiationParcels")]
        public virtual Parcel Parcel { get; set; }
    }
}