// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("NegotiationDocuments", Schema = "SH72")]
    public partial class NegotiationDocument
    {
        [Key]
        public Guid NegotiationDocumentId { get; set; }
        public Guid NegotiationId { get; set; }
        public Guid DocumentId { get; set; }

        [ForeignKey(nameof(DocumentId))]
        [InverseProperty("NegotiationDocuments")]
        public virtual Document Document { get; set; }
        [ForeignKey(nameof(NegotiationId))]
        [InverseProperty(nameof(NegotiationHistory.NegotiationDocuments))]
        public virtual NegotiationHistory Negotiation { get; set; }
    }
}