// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("NegotiationContacts", Schema = "SH72")]
    public partial class NegotiationContact
    {
        [Key]
        public Guid NegotiationContactId { get; set; }
        public Guid NegotiationId { get; set; }
        public Guid ContactInfoId { get; set; }

        [ForeignKey(nameof(ContactInfoId))]
        [InverseProperty("NegotiationContacts")]
        public virtual ContactInfo ContactInfo { get; set; }
        [ForeignKey(nameof(NegotiationId))]
        [InverseProperty(nameof(NegotiationHistory.NegotiationContacts))]
        public virtual NegotiationHistory Negotiation { get; set; }
    }
}