//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentActivity = new HashSet<DocumentActivity>();
            this.DocumentActivity1 = new HashSet<DocumentActivity>();
            this.Agent = new HashSet<Agent>();
            this.Owner = new HashSet<Owner>();
            this.Parcel = new HashSet<Parcel>();
        }
    
        public System.Guid DocumentId { get; set; }
        public string DocumentType { get; set; }
        public byte[] Content { get; set; }
        public string SharePointUrl { get; set; }
        public string AzureBlobId { get; set; }
        public bool TitleInFile { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedDate { get; set; }
        public Nullable<System.DateTimeOffset> QCDate { get; set; }
        public Nullable<System.DateTimeOffset> ApprovedDate { get; set; }
        public Nullable<System.DateTimeOffset> SentDate { get; set; }
        public string RowmTrackingNumber { get; set; }
        public Nullable<System.DateTimeOffset> DeliveredDate { get; set; }
        public Nullable<System.DateTimeOffset> SignedDate { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedFromOwnerDate { get; set; }
        public string ClientTrackingNumber { get; set; }
        public Nullable<System.DateTimeOffset> ClientSignatureDate { get; set; }
        public Nullable<System.DateTimeOffset> ReceivedFromClientDate { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.Guid> DocumentPackage_PackageId { get; set; }
        public string Title { get; set; }
        public string ContentType { get; set; }
        public string SourceFilename { get; set; }
        public Nullable<System.DateTimeOffset> DateRecorded { get; set; }
        public string CheckNo { get; set; }
    
        public virtual DocumentPackage DocumentPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentActivity> DocumentActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentActivity> DocumentActivity1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent> Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owner> Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcel> Parcel { get; set; }
    }
}
