//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentActivity
    {
        public System.Guid ActivityId { get; set; }
        public System.DateTimeOffset ActivityDate { get; set; }
        public string Activity { get; set; }
        public string ActivityNotes { get; set; }
        public System.Guid ParentDocumentId { get; set; }
        public Nullable<System.Guid> ChildDocumentId { get; set; }
        public System.Guid AgentId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Document Document { get; set; }
        public virtual Document Document1 { get; set; }
    }
}
