//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ROWM_Context : DbContext
    {
        public ROWM_Context()
            : base("name=ROWM_Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Contact_Channel> Contact_Channel { get; set; }
        public virtual DbSet<Contact_Purpose> Contact_Purpose { get; set; }
        public virtual DbSet<ContactInfo> ContactInfo { get; set; }
        public virtual DbSet<ContactLog> ContactLog { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Document_Type> Document_Type { get; set; }
        public virtual DbSet<DocumentActivity> DocumentActivity { get; set; }
        public virtual DbSet<DocumentPackage> DocumentPackage { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Ownership> Ownership { get; set; }
        public virtual DbSet<Parcel> Parcel { get; set; }
        public virtual DbSet<Parcel_Status> Parcel_Status { get; set; }
        public virtual DbSet<Repesentation_Type> Repesentation_Type { get; set; }
        public virtual DbSet<Roe_Status> Roe_Status { get; set; }
    }
}
