//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROWM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ownership
    {
        public System.Guid OwnershipId { get; set; }
        public Nullable<System.Guid> ParcelId { get; set; }
        public System.Guid OwnerId { get; set; }
        public int Ownership_t { get; set; }
        public System.DateTimeOffset Created { get; set; }
        public System.DateTimeOffset LastModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual Parcel Parcel { get; set; }
    }
}
