// <auto-generated />
namespace ROWM.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixdocumentfilename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixdocumentfilename));
        
        string IMigrationMetadata.Id
        {
            get { return "201708172216519_fix document filename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
