// <auto-generated />
namespace ROWM.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddaterecorded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddaterecorded));
        
        string IMigrationMetadata.Id
        {
            get { return "201803280313335_added date recorded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
