// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Action_Item_Activity", Schema = "ROWM")]
    public partial class ActionItemActivity
    {
        [Key]
        public Guid ActivityId { get; set; }
        public Guid ActionItemId { get; set; }
        [StringLength(1000)]
        public string Action { get; set; }
        [StringLength(1000)]
        public string OriginalAction { get; set; }
        public int Status { get; set; }
        public int? OriginalStatus { get; set; }
        public DateTimeOffset DueDate { get; set; }
        public DateTimeOffset? OriginalDueDate { get; set; }
        public Guid Assigned { get; set; }
        public Guid? OriginalAssigned { get; set; }
        public Guid? UpdateAgentId { get; set; }
        public DateTimeOffset ActivityDate { get; set; }
        public string Notes { get; set; }

        [ForeignKey(nameof(ActionItemId))]
        [InverseProperty("ActionItemActivities")]
        public virtual ActionItem ActionItem { get; set; }
    }
}