// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Action_Item_Group", Schema = "ROWM")]
    public partial class ActionItemGroup
    {
        public ActionItemGroup()
        {
            ActionItems = new HashSet<ActionItem>();
        }

        [Key]
        public Guid ActionItemGroupId { get; set; }
        [Required]
        [StringLength(50)]
        public string GroupName { get; set; }
        [StringLength(200)]
        public string GroupNameCaption { get; set; }
        [StringLength(200)]
        public string Company { get; set; }
        [Required]
        public bool? CanCreateItem { get; set; }
        [Required]
        public bool? CanPerformItem { get; set; }
        [Required]
        public bool? CanCloseItem { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public int? DisplayOrder { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [Required]
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [InverseProperty(nameof(ActionItem.AssignedGroup))]
        public virtual ICollection<ActionItem> ActionItems { get; set; }
    }
}