// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Action_Item", Schema = "ROWM")]
    public partial class ActionItem
    {
        public ActionItem()
        {
            ActionItemActivities = new HashSet<ActionItemActivity>();
        }

        [Key]
        public Guid ActionItemId { get; set; }
        public Guid? ParcelId { get; set; }
        public Guid? AssignedGroupId { get; set; }
        public Guid? ActivityId { get; set; }
        [Required]
        public string Action { get; set; }
        public DateTimeOffset DueDate { get; set; }
        public int Status { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [Required]
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ActivityId))]
        [InverseProperty(nameof(StatusActivity.ActionItems))]
        public virtual StatusActivity Activity { get; set; }
        [ForeignKey(nameof(AssignedGroupId))]
        [InverseProperty(nameof(ActionItemGroup.ActionItems))]
        public virtual ActionItemGroup AssignedGroup { get; set; }
        [ForeignKey(nameof(ParcelId))]
        [InverseProperty("ActionItems")]
        public virtual Parcel Parcel { get; set; }
        [InverseProperty(nameof(ActionItemActivity.ActionItem))]
        public virtual ICollection<ActionItemActivity> ActionItemActivities { get; set; }
    }
}