// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Agent", Schema = "ROWM")]
    public partial class Agent
    {
        public Agent()
        {
            Appraisals = new HashSet<Appraisal>();
            ContactLogs = new HashSet<ContactLog>();
            DocumentActivities = new HashSet<DocumentActivity>();
            DocumentAgents = new HashSet<DocumentAgent>();
            NegotiationHistories = new HashSet<NegotiationHistory>();
            StatusActivities = new HashSet<StatusActivity>();
        }

        [Key]
        public Guid AgentId { get; set; }
        [Required]
        [StringLength(20)]
        public string AgentName { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty(nameof(Appraisal.Agent))]
        public virtual ICollection<Appraisal> Appraisals { get; set; }
        [InverseProperty(nameof(ContactLog.ContactAgent))]
        public virtual ICollection<ContactLog> ContactLogs { get; set; }
        [InverseProperty(nameof(DocumentActivity.Agent))]
        public virtual ICollection<DocumentActivity> DocumentActivities { get; set; }
        [InverseProperty(nameof(DocumentAgent.AgentAgent))]
        public virtual ICollection<DocumentAgent> DocumentAgents { get; set; }
        [InverseProperty(nameof(NegotiationHistory.Negotiator))]
        public virtual ICollection<NegotiationHistory> NegotiationHistories { get; set; }
        [InverseProperty(nameof(StatusActivity.Agent))]
        public virtual ICollection<StatusActivity> StatusActivities { get; set; }
    }
}