// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Contact_Followup", Schema = "ROWM")]
    [Index(nameof(ChildContactLogId), Name = "IX_ChildContactLogId")]
    [Index(nameof(ParentContactLogId), Name = "IX_ParentContactLogId")]
    public partial class ContactFollowup
    {
        [Key]
        [Column("ID")]
        public Guid Id { get; set; }
        public int FollowupType { get; set; }
        public Guid ParentContactLogId { get; set; }
        public Guid ChildContactLogId { get; set; }

        [ForeignKey(nameof(ChildContactLogId))]
        [InverseProperty(nameof(ContactLog.ContactFollowupChildContactLogs))]
        public virtual ContactLog ChildContactLog { get; set; }
        [ForeignKey(nameof(ParentContactLogId))]
        [InverseProperty(nameof(ContactLog.ContactFollowupParentContactLogs))]
        public virtual ContactLog ParentContactLog { get; set; }
    }
}