// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("ContactInfoContactLogs", Schema = "ROWM")]
    [Index(nameof(ContactInfoContactId), Name = "IX_ContactInfo_ContactId")]
    [Index(nameof(ContactLogContactLogId), Name = "IX_ContactLog_ContactLogId")]
    public partial class ContactInfoContactLog
    {
        [Key]
        [Column("ContactInfo_ContactId")]
        public Guid ContactInfoContactId { get; set; }
        [Key]
        [Column("ContactLog_ContactLogId")]
        public Guid ContactLogContactLogId { get; set; }

        [ForeignKey(nameof(ContactInfoContactId))]
        [InverseProperty(nameof(ContactInfo.ContactInfoContactLogs))]
        public virtual ContactInfo ContactInfoContact { get; set; }
        [ForeignKey(nameof(ContactLogContactLogId))]
        [InverseProperty(nameof(ContactLog.ContactInfoContactLogs))]
        public virtual ContactLog ContactLogContactLog { get; set; }
    }
}