// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("ContactLog", Schema = "ROWM")]
    [Index(nameof(ContactAgentId), Name = "IX_ContactAgentId")]
    [Index(nameof(OwnerOwnerId), Name = "IX_Owner_OwnerId")]
    public partial class ContactLog
    {
        public ContactLog()
        {
            ContactFollowupChildContactLogs = new HashSet<ContactFollowup>();
            ContactFollowupParentContactLogs = new HashSet<ContactFollowup>();
            ContactInfoContactLogs = new HashSet<ContactInfoContactLog>();
            Documents = new HashSet<Document>();
            ParcelContactLogs = new HashSet<ParcelContactLog>();
        }

        [Key]
        public Guid ContactLogId { get; set; }
        public DateTimeOffset DateAdded { get; set; }
        public Guid ContactAgentId { get; set; }
        [StringLength(20)]
        public string ContactChannel { get; set; }
        [StringLength(50)]
        public string ProjectPhase { get; set; }
        [StringLength(200)]
        public string Title { get; set; }
        public string Notes { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        [Column("Owner_OwnerId")]
        public Guid? OwnerOwnerId { get; set; }
        [Column("Landowner_Score")]
        public int? LandownerScore { get; set; }
        public bool IsDeleted { get; set; }

        [ForeignKey(nameof(ContactAgentId))]
        [InverseProperty(nameof(Agent.ContactLogs))]
        public virtual Agent ContactAgent { get; set; }
        [ForeignKey(nameof(OwnerOwnerId))]
        [InverseProperty(nameof(Owner.ContactLogs))]
        public virtual Owner OwnerOwner { get; set; }
        [InverseProperty(nameof(ContactFollowup.ChildContactLog))]
        public virtual ICollection<ContactFollowup> ContactFollowupChildContactLogs { get; set; }
        [InverseProperty(nameof(ContactFollowup.ParentContactLog))]
        public virtual ICollection<ContactFollowup> ContactFollowupParentContactLogs { get; set; }
        [InverseProperty(nameof(ContactInfoContactLog.ContactLogContactLog))]
        public virtual ICollection<ContactInfoContactLog> ContactInfoContactLogs { get; set; }
        [InverseProperty(nameof(Document.ContactLogContactLog))]
        public virtual ICollection<Document> Documents { get; set; }
        [InverseProperty(nameof(ParcelContactLog.ContactLogContactLog))]
        public virtual ICollection<ParcelContactLog> ParcelContactLogs { get; set; }
    }
}