// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Contact_Purpose", Schema = "ROWM")]
    [Index(nameof(MilestoneCode), Name = "IX_MilestoneCode")]
    public partial class ContactPurpose
    {
        [Key]
        [StringLength(50)]
        public string PurposeCode { get; set; }
        [Required]
        [StringLength(50)]
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        [StringLength(40)]
        public string MilestoneCode { get; set; }

        [ForeignKey(nameof(MilestoneCode))]
        [InverseProperty(nameof(ParcelStatus.ContactPurposes))]
        public virtual ParcelStatus MilestoneCodeNavigation { get; set; }
    }
}