// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("ContactInfo", Schema = "ROWM")]
    [Index(nameof(ContactOwnerId), Name = "IX_ContactOwnerId")]
    [Index(nameof(OrganizationId), Name = "IX_OrganizationId")]
    public partial class ContactInfo
    {
        public ContactInfo()
        {
            ContactInfoContactLogs = new HashSet<ContactInfoContactLog>();
            NegotiationContacts = new HashSet<NegotiationContact>();
            NegotiationHistories = new HashSet<NegotiationHistory>();
            ParcelContactInfos = new HashSet<ParcelContactInfo>();
            RoeConditions = new HashSet<RoeCondition>();
        }

        [Key]
        public Guid ContactId { get; set; }
        public bool IsPrimaryContact { get; set; }
        public Guid ContactOwnerId { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        [Required]
        [StringLength(50)]
        public string Representation { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(400)]
        public string StreetAddress { get; set; }
        [StringLength(100)]
        public string City { get; set; }
        [StringLength(20)]
        public string State { get; set; }
        [Column("ZIP")]
        [StringLength(10)]
        public string Zip { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public Guid? OrganizationId { get; set; }
        public bool IsDeleted { get; set; }
        public bool DoNotEmail { get; set; }
        public bool DoNotLetter { get; set; }
        public bool DoNotCallHomePhone { get; set; }
        public bool DoNotCallWorkPhone { get; set; }
        public bool DoNotCallCellPhone { get; set; }
        [StringLength(10)]
        public string PreferredContactMode { get; set; }

        [ForeignKey(nameof(ContactOwnerId))]
        [InverseProperty(nameof(Owner.ContactInfos))]
        public virtual Owner ContactOwner { get; set; }
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("ContactInfos")]
        public virtual Organization Organization { get; set; }
        [ForeignKey(nameof(PreferredContactMode))]
        [InverseProperty("ContactInfos")]
        public virtual PreferredContactMode PreferredContactModeNavigation { get; set; }
        [InverseProperty(nameof(ContactInfoContactLog.ContactInfoContact))]
        public virtual ICollection<ContactInfoContactLog> ContactInfoContactLogs { get; set; }
        [InverseProperty(nameof(NegotiationContact.ContactInfo))]
        public virtual ICollection<NegotiationContact> NegotiationContacts { get; set; }
        [InverseProperty(nameof(NegotiationHistory.Contact))]
        public virtual ICollection<NegotiationHistory> NegotiationHistories { get; set; }
        [InverseProperty(nameof(ParcelContactInfo.ContactInfoContact))]
        public virtual ICollection<ParcelContactInfo> ParcelContactInfos { get; set; }
        [InverseProperty(nameof(RoeCondition.ContactNavigation))]
        public virtual ICollection<RoeCondition> RoeConditions { get; set; }
    }
}