// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("DocumentActivity", Schema = "ROWM")]
    [Index(nameof(AgentId), Name = "IX_AgentId")]
    [Index(nameof(ChildDocumentId), Name = "IX_ChildDocumentId")]
    [Index(nameof(ParentDocumentId), Name = "IX_ParentDocumentId")]
    public partial class DocumentActivity
    {
        [Key]
        public Guid ActivityId { get; set; }
        public DateTimeOffset ActivityDate { get; set; }
        [Required]
        [StringLength(100)]
        public string Activity { get; set; }
        public string ActivityNotes { get; set; }
        public Guid ParentDocumentId { get; set; }
        public Guid? ChildDocumentId { get; set; }
        public Guid AgentId { get; set; }

        [ForeignKey(nameof(AgentId))]
        [InverseProperty("DocumentActivities")]
        public virtual Agent Agent { get; set; }
        [ForeignKey(nameof(ChildDocumentId))]
        [InverseProperty(nameof(Document.DocumentActivityChildDocuments))]
        public virtual Document ChildDocument { get; set; }
        [ForeignKey(nameof(ParentDocumentId))]
        [InverseProperty(nameof(Document.DocumentActivityParentDocuments))]
        public virtual Document ParentDocument { get; set; }
    }
}