// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Document_Type", Schema = "ROWM")]
    [Index(nameof(MilestoneCode), Name = "IX_MilestoneCode")]
    public partial class DocumentType
    {
        public DocumentType()
        {
            Documents = new HashSet<Document>();
        }

        [Key]
        [StringLength(200)]
        public string DocTypeName { get; set; }
        public string Description { get; set; }
        [StringLength(400)]
        public string FolderPath { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        [StringLength(40)]
        public string MilestoneCode { get; set; }

        [ForeignKey(nameof(MilestoneCode))]
        [InverseProperty(nameof(ParcelStatus.DocumentTypes))]
        public virtual ParcelStatus MilestoneCodeNavigation { get; set; }
        [InverseProperty(nameof(Document.DocumentTypeNavigation))]
        public virtual ICollection<Document> Documents { get; set; }
    }
}