// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("DocumentPackage", Schema = "ROWM")]
    public partial class DocumentPackage
    {
        public DocumentPackage()
        {
            Appraisals = new HashSet<Appraisal>();
            Documents = new HashSet<Document>();
        }

        [Key]
        public Guid PackageId { get; set; }
        [Required]
        [StringLength(100)]
        public string PackageName { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [InverseProperty(nameof(Appraisal.Report))]
        public virtual ICollection<Appraisal> Appraisals { get; set; }
        [InverseProperty(nameof(Document.DocumentPackagePackage))]
        public virtual ICollection<Document> Documents { get; set; }
    }
}