// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("DocumentAgents", Schema = "ROWM")]
    [Index(nameof(AgentAgentId), Name = "IX_Agent_AgentId")]
    [Index(nameof(DocumentDocumentId), Name = "IX_Document_DocumentId")]
    public partial class DocumentAgent
    {
        [Key]
        [Column("Agent_AgentId")]
        public Guid AgentAgentId { get; set; }
        [Key]
        [Column("Document_DocumentId")]
        public Guid DocumentDocumentId { get; set; }

        [ForeignKey(nameof(AgentAgentId))]
        [InverseProperty(nameof(Agent.DocumentAgents))]
        public virtual Agent AgentAgent { get; set; }
        [ForeignKey(nameof(DocumentDocumentId))]
        [InverseProperty(nameof(Document.DocumentAgents))]
        public virtual Document DocumentDocument { get; set; }
    }
}