// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Organization", Schema = "ROWM")]
    public partial class Organization
    {
        public Organization()
        {
            ContactInfos = new HashSet<ContactInfo>();
        }

        [Key]
        public Guid OrganizationId { get; set; }
        public string Name { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [InverseProperty(nameof(ContactInfo.Organization))]
        public virtual ICollection<ContactInfo> ContactInfos { get; set; }
    }
}