// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("OwnerDocuments", Schema = "ROWM")]
    [Index(nameof(DocumentDocumentId), Name = "IX_Document_DocumentId")]
    [Index(nameof(OwnerOwnerId), Name = "IX_Owner_OwnerId")]
    public partial class OwnerDocument
    {
        [Key]
        [Column("Document_DocumentId")]
        public Guid DocumentDocumentId { get; set; }
        [Key]
        [Column("Owner_OwnerId")]
        public Guid OwnerOwnerId { get; set; }

        [ForeignKey(nameof(DocumentDocumentId))]
        [InverseProperty(nameof(Document.OwnerDocuments))]
        public virtual Document DocumentDocument { get; set; }
        [ForeignKey(nameof(OwnerOwnerId))]
        [InverseProperty(nameof(Owner.OwnerDocuments))]
        public virtual Owner OwnerOwner { get; set; }
    }
}