// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Ownership", Schema = "ROWM")]
    [Index(nameof(OwnerId), Name = "IX_OwnerId")]
    [Index(nameof(ParcelId), Name = "IX_ParcelId")]
    public partial class Ownership
    {
        [Key]
        public Guid OwnershipId { get; set; }
        public Guid? ParcelId { get; set; }
        public Guid OwnerId { get; set; }
        [Column("Ownership_t")]
        public int OwnershipT { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(OwnerId))]
        [InverseProperty("Ownerships")]
        public virtual Owner Owner { get; set; }
        [ForeignKey(nameof(ParcelId))]
        [InverseProperty("Ownerships")]
        public virtual Parcel Parcel { get; set; }
    }
}