// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Parcel_Allocation", Schema = "ROWM")]
    [Index(nameof(ProjectPartId), nameof(ParcelId), Name = "U_Allocation", IsUnique = true)]
    public partial class ParcelAllocation
    {
        [Key]
        public Guid AllocationId { get; set; }
        public int ProjectPartId { get; set; }
        public Guid ParcelId { get; set; }
        [Required]
        [StringLength(50)]
        public string TrackingNumber { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [Required]
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ParcelId))]
        [InverseProperty("ParcelAllocations")]
        public virtual Parcel Parcel { get; set; }
        [ForeignKey(nameof(ProjectPartId))]
        [InverseProperty("ParcelAllocations")]
        public virtual ProjectPart ProjectPart { get; set; }
    }
}