// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Parcel_Status", Schema = "ROWM")]
    public partial class ParcelStatus
    {
        public ParcelStatus()
        {
            ContactPurposes = new HashSet<ContactPurpose>();
            DocumentTypes = new HashSet<DocumentType>();
            Parcels = new HashSet<Parcel>();
        }

        [Key]
        [StringLength(40)]
        public string Code { get; set; }
        public int DomainValue { get; set; }
        [StringLength(50)]
        public string Category { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool? IsComplete { get; set; }
        public bool? IsAbort { get; set; }
        [StringLength(40)]
        public string ParentStatusCode { get; set; }
        public bool? IsRequired { get; set; }
        public bool? IsComputed { get; set; }
        public bool? ShowInPie { get; set; }

        [ForeignKey(nameof(Category))]
        [InverseProperty(nameof(StatusCategory.ParcelStatuses))]
        public virtual StatusCategory CategoryNavigation { get; set; }
        [InverseProperty(nameof(ContactPurpose.MilestoneCodeNavigation))]
        public virtual ICollection<ContactPurpose> ContactPurposes { get; set; }
        [InverseProperty(nameof(DocumentType.MilestoneCodeNavigation))]
        public virtual ICollection<DocumentType> DocumentTypes { get; set; }
        [InverseProperty(nameof(Parcel.ParcelStatusCodeNavigation))]
        public virtual ICollection<Parcel> Parcels { get; set; }
    }
}