// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("ParcelDocuments", Schema = "ROWM")]
    [Index(nameof(DocumentDocumentId), Name = "IX_Document_DocumentId")]
    [Index(nameof(ParcelParcelId), Name = "IX_Parcel_ParcelId")]
    public partial class ParcelDocument
    {
        [Key]
        [Column("Document_DocumentId")]
        public Guid DocumentDocumentId { get; set; }
        [Key]
        [Column("Parcel_ParcelId")]
        public Guid ParcelParcelId { get; set; }

        [ForeignKey(nameof(DocumentDocumentId))]
        [InverseProperty(nameof(Document.ParcelDocuments))]
        public virtual Document DocumentDocument { get; set; }
        [ForeignKey(nameof(ParcelParcelId))]
        [InverseProperty(nameof(Parcel.ParcelDocuments))]
        public virtual Parcel ParcelParcel { get; set; }
    }
}