// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("ParcelContactInfo", Schema = "ROWM")]
    [Index(nameof(ContactInfoContactId), Name = "IX_ContactInfo_ContactId")]
    [Index(nameof(ParcelParcelId), Name = "IX_Parcel_ParcelId")]
    public partial class ParcelContactInfo
    {
        [Key]
        [Column("Parcel_ParcelId")]
        public Guid ParcelParcelId { get; set; }
        [Key]
        [Column("ContactInfo_ContactId")]
        public Guid ContactInfoContactId { get; set; }

        [ForeignKey(nameof(ContactInfoContactId))]
        [InverseProperty(nameof(ContactInfo.ParcelContactInfos))]
        public virtual ContactInfo ContactInfoContact { get; set; }
        [ForeignKey(nameof(ParcelParcelId))]
        [InverseProperty(nameof(Parcel.ParcelContactInfos))]
        public virtual Parcel ParcelParcel { get; set; }
    }
}