// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Keyless]
    [Table("Parcel_Node", Schema = "ROWM")]
    public partial class ParcelNode
    {
        [Required]
        [Column("$node_id_E0EE27B3CAA74FCC8CD9E539760863F2")]
        [StringLength(1000)]
        public string NodeIdE0ee27b3caa74fcc8cd9e539760863f2 { get; set; }
        public Guid ParcelId { get; set; }
        [Required]
        [Column("Assessor_Parcel_Number")]
        [StringLength(128)]
        public string AssessorParcelNumber { get; set; }
    }
}