// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Preferred_Contact_Mode", Schema = "ROWM")]
    public partial class PreferredContactMode
    {
        public PreferredContactMode()
        {
            ContactInfos = new HashSet<ContactInfo>();
        }

        [Key]
        [StringLength(10)]
        public string Mode { get; set; }
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty(nameof(ContactInfo.PreferredContactModeNavigation))]
        public virtual ICollection<ContactInfo> ContactInfos { get; set; }
    }
}