// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Project_Part", Schema = "ROWM")]
    public partial class ProjectPart
    {
        public ProjectPart()
        {
            Maps = new HashSet<Map>();
            ParcelAllocations = new HashSet<ParcelAllocation>();
        }

        [Key]
        public int ProjectPartId { get; set; }
        [Required]
        [StringLength(200)]
        public string Caption { get; set; }
        public int DisplayOrder { get; set; }
        public DateTimeOffset? ScheduleStart { get; set; }
        public DateTimeOffset? ScheduleCompletion { get; set; }
        public DateTimeOffset? ActualStart { get; set; }
        public DateTimeOffset? ActualCompletion { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [Required]
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [InverseProperty(nameof(Map.ProjectPart))]
        public virtual ICollection<Map> Maps { get; set; }
        [InverseProperty(nameof(ParcelAllocation.ProjectPart))]
        public virtual ICollection<ParcelAllocation> ParcelAllocations { get; set; }
    }
}