// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Status_Category", Schema = "ROWM")]
    public partial class StatusCategory
    {
        public StatusCategory()
        {
            ParcelStatuses = new HashSet<ParcelStatus>();
        }

        [Key]
        [StringLength(50)]
        public string CategoryCode { get; set; }
        public string Description { get; set; }
        public int? DisplayOrder { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty(nameof(ParcelStatus.CategoryNavigation))]
        public virtual ICollection<ParcelStatus> ParcelStatuses { get; set; }
    }
}