// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Status_Activity", Schema = "ROWM")]
    public partial class StatusActivity
    {
        public StatusActivity()
        {
            ActionItems = new HashSet<ActionItem>();
        }

        [Key]
        public Guid ActivityId { get; set; }
        public DateTimeOffset ActivityDate { get; set; }
        public Guid ParentParcelId { get; set; }
        public Guid AgentId { get; set; }
        [Required]
        [StringLength(50)]
        public string StatusCode { get; set; }
        [StringLength(50)]
        public string OriginalStatusCode { get; set; }
        public string Notes { get; set; }

        [ForeignKey(nameof(AgentId))]
        [InverseProperty("StatusActivities")]
        public virtual Agent Agent { get; set; }
        [InverseProperty(nameof(ActionItem.Activity))]
        public virtual ICollection<ActionItem> ActionItems { get; set; }
    }
}