// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ActionItemConfiguration : IEntityTypeConfiguration<ActionItem>
    {
        public void Configure(EntityTypeBuilder<ActionItem> entity)
        {
            entity.Property(e => e.ActionItemId).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Activity)
                .WithMany(p => p.ActionItems)
                .HasForeignKey(d => d.ActivityId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ACTION_ITEM");

            entity.HasOne(d => d.AssignedGroup)
                .WithMany(p => p.ActionItems)
                .HasForeignKey(d => d.AssignedGroupId)
                .HasConstraintName("FK_Action_Item_Assignment");

            entity.HasOne(d => d.Parcel)
                .WithMany(p => p.ActionItems)
                .HasForeignKey(d => d.ParcelId)
                .HasConstraintName("FK_Action_Item_Parcel");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActionItem> entity);
    }
}
