// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ActionItemGroupConfiguration : IEntityTypeConfiguration<ActionItemGroup>
    {
        public void Configure(EntityTypeBuilder<ActionItemGroup> entity)
        {
            entity.Property(e => e.ActionItemGroupId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.CanCloseItem).HasDefaultValueSql("((1))");

            entity.Property(e => e.CanCreateItem).HasDefaultValueSql("((1))");

            entity.Property(e => e.CanPerformItem).HasDefaultValueSql("((1))");

            entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActionItemGroup> entity);
    }
}
