// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ActionItemActivityConfiguration : IEntityTypeConfiguration<ActionItemActivity>
    {
        public void Configure(EntityTypeBuilder<ActionItemActivity> entity)
        {
            entity.HasKey(e => e.ActivityId)
                .HasName("PK_Action_Item_History");

            entity.Property(e => e.ActivityId).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.ActionItem)
                .WithMany(p => p.ActionItemActivities)
                .HasForeignKey(d => d.ActionItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Action_Item_Activity_Action_Item");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActionItemActivity> entity);
    }
}
