// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class AppraisalConfiguration : IEntityTypeConfiguration<Appraisal>
    {
        public void Configure(EntityTypeBuilder<Appraisal> entity)
        {
            entity.Property(e => e.AppraisalId).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Agent)
                .WithMany(p => p.Appraisals)
                .HasForeignKey(d => d.AgentId)
                .HasConstraintName("FK_Appraisal_Agent");

            entity.HasOne(d => d.Parcel)
                .WithMany(p => p.Appraisals)
                .HasForeignKey(d => d.ParcelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Appraisal_Parcel");

            entity.HasOne(d => d.Report)
                .WithMany(p => p.Appraisals)
                .HasForeignKey(d => d.ReportId)
                .HasConstraintName("FK_Appraisal_DocumentPackage");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Appraisal> entity);
    }
}
