// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ContactLogConfiguration : IEntityTypeConfiguration<ContactLog>
    {
        public void Configure(EntityTypeBuilder<ContactLog> entity)
        {
            entity.Property(e => e.ContactLogId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.ContactAgent)
                .WithMany(p => p.ContactLogs)
                .HasForeignKey(d => d.ContactAgentId)
                .HasConstraintName("FK_ROWM.ContactLog_ROWM.Agent_ContactAgentId");

            entity.HasOne(d => d.OwnerOwner)
                .WithMany(p => p.ContactLogs)
                .HasForeignKey(d => d.OwnerOwnerId)
                .HasConstraintName("FK_ROWM.ContactLog_ROWM.Owner_Owner_OwnerId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactLog> entity);
    }
}
