// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ContactChannelConfiguration : IEntityTypeConfiguration<ContactChannel>
    {
        public void Configure(EntityTypeBuilder<ContactChannel> entity)
        {
            entity.HasKey(e => e.ContactTypeCode)
                .HasName("PK_ROWM.Contact_Channel");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactChannel> entity);
    }
}
