// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ContactInfoConfiguration : IEntityTypeConfiguration<ContactInfo>
    {
        public void Configure(EntityTypeBuilder<ContactInfo> entity)
        {
            entity.HasKey(e => e.ContactId)
                .HasName("PK_ROWM.ContactInfo");

            entity.Property(e => e.ContactId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.ContactOwner)
                .WithMany(p => p.ContactInfos)
                .HasForeignKey(d => d.ContactOwnerId)
                .HasConstraintName("FK_ROWM.ContactInfo_ROWM.Owner_ContactOwnerId");

            entity.HasOne(d => d.Organization)
                .WithMany(p => p.ContactInfos)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK_ROWM.ContactInfo_ROWM.Organization_OrganizationId");

            entity.HasOne(d => d.PreferredContactModeNavigation)
                .WithMany(p => p.ContactInfos)
                .HasForeignKey(d => d.PreferredContactMode)
                .HasConstraintName("FK_MODE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactInfo> entity);
    }
}
