// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ContactFollowupConfiguration : IEntityTypeConfiguration<ContactFollowup>
    {
        public void Configure(EntityTypeBuilder<ContactFollowup> entity)
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.ChildContactLog)
                .WithMany(p => p.ContactFollowupChildContactLogs)
                .HasForeignKey(d => d.ChildContactLogId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ROWM.Contact_Followup_ROWM.ContactLog_ChildContactLogId");

            entity.HasOne(d => d.ParentContactLog)
                .WithMany(p => p.ContactFollowupParentContactLogs)
                .HasForeignKey(d => d.ParentContactLogId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ROWM.Contact_Followup_ROWM.ContactLog_ParentContactLogId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactFollowup> entity);
    }
}
