// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ContactInfoContactLogConfiguration : IEntityTypeConfiguration<ContactInfoContactLog>
    {
        public void Configure(EntityTypeBuilder<ContactInfoContactLog> entity)
        {
            entity.HasKey(e => new { e.ContactInfoContactId, e.ContactLogContactLogId })
                .HasName("PK_ROWM.ContactInfoContactLogs");

            entity.HasOne(d => d.ContactInfoContact)
                .WithMany(p => p.ContactInfoContactLogs)
                .HasForeignKey(d => d.ContactInfoContactId)
                .HasConstraintName("FK_ROWM.ContactInfoContactLogs_ROWM.ContactInfo_ContactInfo_ContactId");

            entity.HasOne(d => d.ContactLogContactLog)
                .WithMany(p => p.ContactInfoContactLogs)
                .HasForeignKey(d => d.ContactLogContactLogId)
                .HasConstraintName("FK_ROWM.ContactInfoContactLogs_ROWM.ContactLog_ContactLog_ContactLogId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactInfoContactLog> entity);
    }
}
