// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ContactPurposeConfiguration : IEntityTypeConfiguration<ContactPurpose>
    {
        public void Configure(EntityTypeBuilder<ContactPurpose> entity)
        {
            entity.HasKey(e => e.PurposeCode)
                .HasName("PK_ROWM.Contact_Purpose");

            entity.HasOne(d => d.MilestoneCodeNavigation)
                .WithMany(p => p.ContactPurposes)
                .HasForeignKey(d => d.MilestoneCode)
                .HasConstraintName("FK_ROWM.Contact_Purpose_ROWM.Parcel_Status_MilestoneCode");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactPurpose> entity);
    }
}
