// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class CostEstimateConfiguration : IEntityTypeConfiguration<CostEstimate>
    {
        public void Configure(EntityTypeBuilder<CostEstimate> entity)
        {
            entity.Property(e => e.EstimateId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.DesignMilestone).IsUnicode(false);

            entity.Property(e => e.Line).IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CostEstimate> entity);
    }
}
