// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class DocumentConfiguration : IEntityTypeConfiguration<Document>
    {
        public void Configure(EntityTypeBuilder<Document> entity)
        {
            entity.Property(e => e.DocumentId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.ContactLogContactLog)
                .WithMany(p => p.Documents)
                .HasForeignKey(d => d.ContactLogContactLogId)
                .HasConstraintName("FK_ROWM.Document_ROWM.ContactLog_ContactLog_ContactLogId");

            entity.HasOne(d => d.DocumentPackagePackage)
                .WithMany(p => p.Documents)
                .HasForeignKey(d => d.DocumentPackagePackageId)
                .HasConstraintName("FK_ROWM.Document_ROWM.DocumentPackage_DocumentPackage_PackageId");

            entity.HasOne(d => d.DocumentTypeNavigation)
                .WithMany(p => p.Documents)
                .HasForeignKey(d => d.DocumentType)
                .HasConstraintName("FK_Document_Document_Type");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Document> entity);
    }
}
