// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class DocumentActivityConfiguration : IEntityTypeConfiguration<DocumentActivity>
    {
        public void Configure(EntityTypeBuilder<DocumentActivity> entity)
        {
            entity.HasKey(e => e.ActivityId)
                .HasName("PK_ROWM.DocumentActivity");

            entity.Property(e => e.ActivityId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.Agent)
                .WithMany(p => p.DocumentActivities)
                .HasForeignKey(d => d.AgentId)
                .HasConstraintName("FK_ROWM.DocumentActivity_ROWM.Agent_AgentId");

            entity.HasOne(d => d.ChildDocument)
                .WithMany(p => p.DocumentActivityChildDocuments)
                .HasForeignKey(d => d.ChildDocumentId)
                .HasConstraintName("FK_ROWM.DocumentActivity_ROWM.Document_ChildDocumentId");

            entity.HasOne(d => d.ParentDocument)
                .WithMany(p => p.DocumentActivityParentDocuments)
                .HasForeignKey(d => d.ParentDocumentId)
                .HasConstraintName("FK_ROWM.DocumentActivity_ROWM.Document_ParentDocumentId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentActivity> entity);
    }
}
