// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class DocumentPackageConfiguration : IEntityTypeConfiguration<DocumentPackage>
    {
        public void Configure(EntityTypeBuilder<DocumentPackage> entity)
        {
            entity.HasKey(e => e.PackageId)
                .HasName("PK_ROWM.DocumentPackage");

            entity.Property(e => e.PackageId).HasDefaultValueSql("(newsequentialid())");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentPackage> entity);
    }
}
