// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class DocumentAgentConfiguration : IEntityTypeConfiguration<DocumentAgent>
    {
        public void Configure(EntityTypeBuilder<DocumentAgent> entity)
        {
            entity.HasKey(e => new { e.AgentAgentId, e.DocumentDocumentId })
                .HasName("PK_ROWM.DocumentAgents");

            entity.HasOne(d => d.AgentAgent)
                .WithMany(p => p.DocumentAgents)
                .HasForeignKey(d => d.AgentAgentId)
                .HasConstraintName("FK_ROWM.DocumentAgents_ROWM.Agent_Agent_AgentId");

            entity.HasOne(d => d.DocumentDocument)
                .WithMany(p => p.DocumentAgents)
                .HasForeignKey(d => d.DocumentDocumentId)
                .HasConstraintName("FK_ROWM.DocumentAgents_ROWM.Document_Document_DocumentId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocumentAgent> entity);
    }
}
