// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class LandownerScoreConfiguration : IEntityTypeConfiguration<LandownerScore>
    {
        public void Configure(EntityTypeBuilder<LandownerScore> entity)
        {
            entity.HasKey(e => e.Score)
                .HasName("PK_ROWM.Landowner_Score");

            entity.Property(e => e.Score).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LandownerScore> entity);
    }
}
