// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class NegotiationHistoryConfiguration : IEntityTypeConfiguration<NegotiationHistory>
    {
        public void Configure(EntityTypeBuilder<NegotiationHistory> entity)
        {
            entity.Property(e => e.NegotiationId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.LastModified).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Contact)
                .WithMany(p => p.NegotiationHistories)
                .HasForeignKey(d => d.ContactId)
                .HasConstraintName("FK_Negotiation_History_ContactInfo");

            entity.HasOne(d => d.Negotiator)
                .WithMany(p => p.NegotiationHistories)
                .HasForeignKey(d => d.NegotiatorId)
                .HasConstraintName("FK_Negotiation_History_Agent");

            entity.HasOne(d => d.Owner)
                .WithMany(p => p.NegotiationHistories)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Negotiation_History_Owner");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NegotiationHistory> entity);
    }
}
