// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class NegotiationParcelConfiguration : IEntityTypeConfiguration<NegotiationParcel>
    {
        public void Configure(EntityTypeBuilder<NegotiationParcel> entity)
        {
            entity.Property(e => e.NegotiationParcelId).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Negotiation)
                .WithMany(p => p.NegotiationParcels)
                .HasForeignKey(d => d.NegotiationId)
                .HasConstraintName("FK_NegotiationParcels_Negotiation_History");

            entity.HasOne(d => d.Parcel)
                .WithMany(p => p.NegotiationParcels)
                .HasForeignKey(d => d.ParcelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NegotiationParcels_Parcel");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NegotiationParcel> entity);
    }
}
