// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class NegotiationDocumentConfiguration : IEntityTypeConfiguration<NegotiationDocument>
    {
        public void Configure(EntityTypeBuilder<NegotiationDocument> entity)
        {
            entity.Property(e => e.NegotiationDocumentId).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Document)
                .WithMany(p => p.NegotiationDocuments)
                .HasForeignKey(d => d.DocumentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NegotiationDocuments_Document");

            entity.HasOne(d => d.Negotiation)
                .WithMany(p => p.NegotiationDocuments)
                .HasForeignKey(d => d.NegotiationId)
                .HasConstraintName("FK_NegotiationDocuments_Negotiation_History");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NegotiationDocument> entity);
    }
}
