// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class NegotiationContactConfiguration : IEntityTypeConfiguration<NegotiationContact>
    {
        public void Configure(EntityTypeBuilder<NegotiationContact> entity)
        {
            entity.Property(e => e.NegotiationContactId).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.ContactInfo)
                .WithMany(p => p.NegotiationContacts)
                .HasForeignKey(d => d.ContactInfoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NegotiationContacts_ContactInfo");

            entity.HasOne(d => d.Negotiation)
                .WithMany(p => p.NegotiationContacts)
                .HasForeignKey(d => d.NegotiationId)
                .HasConstraintName("FK_NegotiationContacts_Negotiation_History");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NegotiationContact> entity);
    }
}
