// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class OwnershipConfiguration : IEntityTypeConfiguration<Ownership>
    {
        public void Configure(EntityTypeBuilder<Ownership> entity)
        {
            entity.Property(e => e.OwnershipId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.Owner)
                .WithMany(p => p.Ownerships)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("FK_ROWM.Ownership_ROWM.Owner_OwnerId");

            entity.HasOne(d => d.Parcel)
                .WithMany(p => p.Ownerships)
                .HasForeignKey(d => d.ParcelId)
                .HasConstraintName("FK_ROWM.Ownership_ROWM.Parcel_ParcelId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Ownership> entity);
    }
}
