// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class OwnerDocumentConfiguration : IEntityTypeConfiguration<OwnerDocument>
    {
        public void Configure(EntityTypeBuilder<OwnerDocument> entity)
        {
            entity.HasKey(e => new { e.DocumentDocumentId, e.OwnerOwnerId })
                .HasName("PK_ROWM.OwnerDocuments");

            entity.HasOne(d => d.DocumentDocument)
                .WithMany(p => p.OwnerDocuments)
                .HasForeignKey(d => d.DocumentDocumentId)
                .HasConstraintName("FK_ROWM.OwnerDocuments_ROWM.Document_Document_DocumentId");

            entity.HasOne(d => d.OwnerOwner)
                .WithMany(p => p.OwnerDocuments)
                .HasForeignKey(d => d.OwnerOwnerId)
                .HasConstraintName("FK_ROWM.OwnerDocuments_ROWM.Owner_Owner_OwnerId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OwnerDocument> entity);
    }
}
