// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class OwnerConfiguration : IEntityTypeConfiguration<Owner>
    {
        public void Configure(EntityTypeBuilder<Owner> entity)
        {
            entity.Property(e => e.OwnerId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.OwnerOwner)
                .WithMany(p => p.InverseOwnerOwner)
                .HasForeignKey(d => d.OwnerOwnerId)
                .HasConstraintName("FK_ROWM.Owner_ROWM.Owner_Owner_OwnerId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Owner> entity);
    }
}
