// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ParcelContactInfoConfiguration : IEntityTypeConfiguration<ParcelContactInfo>
    {
        public void Configure(EntityTypeBuilder<ParcelContactInfo> entity)
        {
            entity.HasKey(e => new { e.ContactInfoContactId, e.ParcelParcelId })
                .HasName("PK_ROWM.ParcelContactInfo");

            entity.HasOne(d => d.ContactInfoContact)
                .WithMany(p => p.ParcelContactInfos)
                .HasForeignKey(d => d.ContactInfoContactId)
                .HasConstraintName("FK_dbo.ParcelContactInfoes_ROWM.ContactInfo_ContactInfo_ContactId");

            entity.HasOne(d => d.ParcelParcel)
                .WithMany(p => p.ParcelContactInfos)
                .HasForeignKey(d => d.ParcelParcelId)
                .HasConstraintName("FK_dbo.ParcelContactInfoes_ROWM.Parcel_Parcel_ParcelId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParcelContactInfo> entity);
    }
}
