// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ParcelAllocationConfiguration : IEntityTypeConfiguration<ParcelAllocation>
    {
        public void Configure(EntityTypeBuilder<ParcelAllocation> entity)
        {
            entity.Property(e => e.AllocationId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");

            entity.Property(e => e.LastModified).HasDefaultValueSql("(getdate())");

            entity.Property(e => e.TrackingNumber).IsUnicode(false);

            entity.HasOne(d => d.Parcel)
                .WithMany(p => p.ParcelAllocations)
                .HasForeignKey(d => d.ParcelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Parcel");

            entity.HasOne(d => d.ProjectPart)
                .WithMany(p => p.ParcelAllocations)
                .HasForeignKey(d => d.ProjectPartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Part");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParcelAllocation> entity);
    }
}
