// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ParcelContactLogConfiguration : IEntityTypeConfiguration<ParcelContactLog>
    {
        public void Configure(EntityTypeBuilder<ParcelContactLog> entity)
        {
            entity.HasKey(e => new { e.ContactLogContactLogId, e.ParcelParcelId })
                .HasName("PK_ROWM.ParcelContactLogs");

            entity.HasOne(d => d.ContactLogContactLog)
                .WithMany(p => p.ParcelContactLogs)
                .HasForeignKey(d => d.ContactLogContactLogId)
                .HasConstraintName("FK_ROWM.ParcelContactLogs_ROWM.ContactLog_ContactLog_ContactLogId");

            entity.HasOne(d => d.ParcelParcel)
                .WithMany(p => p.ParcelContactLogs)
                .HasForeignKey(d => d.ParcelParcelId)
                .HasConstraintName("FK_ROWM.ParcelContactLogs_ROWM.Parcel_Parcel_ParcelId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParcelContactLog> entity);
    }
}
