// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ParcelConfiguration : IEntityTypeConfiguration<Parcel>
    {
        public void Configure(EntityTypeBuilder<Parcel> entity)
        {
            entity.Property(e => e.ParcelId).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.CountyFips)
                .IsUnicode(false)
                .IsFixedLength(true);

            entity.HasOne(d => d.ParcelParcel)
                .WithMany(p => p.InverseParcelParcel)
                .HasForeignKey(d => d.ParcelParcelId)
                .HasConstraintName("FK_ROWM.Parcel_ROWM.Parcel_Parcel_ParcelId");

            entity.HasOne(d => d.ParcelStatusCodeNavigation)
                .WithMany(p => p.Parcels)
                .HasForeignKey(d => d.ParcelStatusCode)
                .HasConstraintName("FK_ROWM.Parcel_ROWM.Parcel_Status_ParcelStatusCode");

            entity.HasOne(d => d.RoeStatusCodeNavigation)
                .WithMany(p => p.Parcels)
                .HasForeignKey(d => d.RoeStatusCode)
                .HasConstraintName("FK_ROWM.Parcel_ROWM.Roe_Status_RoeStatusCode");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Parcel> entity);
    }
}
