// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ParcelDocumentConfiguration : IEntityTypeConfiguration<ParcelDocument>
    {
        public void Configure(EntityTypeBuilder<ParcelDocument> entity)
        {
            entity.HasKey(e => new { e.DocumentDocumentId, e.ParcelParcelId })
                .HasName("PK_ROWM.ParcelDocuments");

            entity.HasOne(d => d.DocumentDocument)
                .WithMany(p => p.ParcelDocuments)
                .HasForeignKey(d => d.DocumentDocumentId)
                .HasConstraintName("FK_ROWM.ParcelDocuments_ROWM.Document_Document_DocumentId");

            entity.HasOne(d => d.ParcelParcel)
                .WithMany(p => p.ParcelDocuments)
                .HasForeignKey(d => d.ParcelParcelId)
                .HasConstraintName("FK_ROWM.ParcelDocuments_ROWM.Parcel_Parcel_ParcelId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParcelDocument> entity);
    }
}
