// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class ParcelStatusConfiguration : IEntityTypeConfiguration<ParcelStatus>
    {
        public void Configure(EntityTypeBuilder<ParcelStatus> entity)
        {
            entity.HasKey(e => e.Code)
                .HasName("PK_ROWM.Parcel_Status");

            entity.Property(e => e.Category).IsUnicode(false);

            entity.HasOne(d => d.CategoryNavigation)
                .WithMany(p => p.ParcelStatuses)
                .HasForeignKey(d => d.Category)
                .HasConstraintName("FK_Parcel_Status_Category");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParcelStatus> entity);
    }
}
