// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class PreferredContactModeConfiguration : IEntityTypeConfiguration<PreferredContactMode>
    {
        public void Configure(EntityTypeBuilder<PreferredContactMode> entity)
        {
            entity.HasKey(e => e.Mode)
                .HasName("PK__Preferre__2488AC273F1BD714");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PreferredContactMode> entity);
    }
}
