// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class RelocationActivityTypeConfiguration : IEntityTypeConfiguration<RelocationActivityType>
    {
        public void Configure(EntityTypeBuilder<RelocationActivityType> entity)
        {
            entity.HasKey(e => e.ActivityTypeCode)
                .HasName("PK_Austin.Relocation_Activity_Type");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RelocationActivityType> entity);
    }
}
