// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class RelocationDisplaceeActivityConfiguration : IEntityTypeConfiguration<RelocationDisplaceeActivity>
    {
        public void Configure(EntityTypeBuilder<RelocationDisplaceeActivity> entity)
        {
            entity.HasKey(e => e.ActivityId)
                .HasName("PK_Austin.Relocation_Displacee_Activity");

            entity.Property(e => e.ActivityId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.ActivityCodeNavigation)
                .WithMany(p => p.RelocationDisplaceeActivities)
                .HasForeignKey(d => d.ActivityCode)
                .HasConstraintName("FK_Austin.Relocation_Displacee_Activity_Austin.Relocation_Activity_Type_ActivityCode");

            entity.HasOne(d => d.Case)
                .WithMany(p => p.RelocationDisplaceeActivities)
                .HasForeignKey(d => d.CaseId)
                .HasConstraintName("FK_Austin.Relocation_Displacee_Activity_Austin.Relocation_Case_CaseId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RelocationDisplaceeActivity> entity);
    }
}
