// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class RelocationCaseConfiguration : IEntityTypeConfiguration<RelocationCase>
    {
        public void Configure(EntityTypeBuilder<RelocationCase> entity)
        {
            entity.Property(e => e.RelocationCaseId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.ParentRelocation)
                .WithMany(p => p.RelocationCases)
                .HasForeignKey(d => d.ParentRelocationId)
                .HasConstraintName("FK_Austin.Relocation_Case_Austin.Parcel_Relocation_ParentRelocationId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RelocationCase> entity);
    }
}
