// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class RelocationEligibilityConfiguration : IEntityTypeConfiguration<RelocationEligibility>
    {
        public void Configure(EntityTypeBuilder<RelocationEligibility> entity)
        {
            entity.HasKey(e => e.ActivityId)
                .HasName("PK_Austin.Relocation_Eligibility");

            entity.Property(e => e.ActivityId).HasDefaultValueSql("(newsequentialid())");

            entity.HasOne(d => d.Case)
                .WithMany(p => p.RelocationEligibilities)
                .HasForeignKey(d => d.CaseId)
                .HasConstraintName("FK_Austin.Relocation_Eligibility_Austin.Relocation_Case_CaseId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RelocationEligibility> entity);
    }
}
