// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class RepresentationTypeConfiguration : IEntityTypeConfiguration<RepresentationType>
    {
        public void Configure(EntityTypeBuilder<RepresentationType> entity)
        {
            entity.HasKey(e => e.RelationTypeCode)
                .HasName("PK_ROWM.Repesentation_Type");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RepresentationType> entity);
    }
}
