// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class RoeConditionConfiguration : IEntityTypeConfiguration<RoeCondition>
    {
        public void Configure(EntityTypeBuilder<RoeCondition> entity)
        {
            entity.HasKey(e => e.ConditionId)
                .HasName("PK_dbo.RoeConditions");

            entity.Property(e => e.ConditionId).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.ContactNavigation)
                .WithMany(p => p.RoeConditions)
                .HasForeignKey(d => d.Contact)
                .HasConstraintName("FK_CONDITIONS_CONTACTINFO");

            entity.HasOne(d => d.ParcelParcel)
                .WithMany(p => p.RoeConditions)
                .HasForeignKey(d => d.ParcelParcelId)
                .HasConstraintName("FK_dbo.RoeConditions_ROWM.Parcel_Parcel_ParcelId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoeCondition> entity);
    }
}
