// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class RoeStatusConfiguration : IEntityTypeConfiguration<RoeStatus>
    {
        public void Configure(EntityTypeBuilder<RoeStatus> entity)
        {
            entity.HasKey(e => e.Code)
                .HasName("PK_ROWM.Roe_Status");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RoeStatus> entity);
    }
}
