// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class StatusActivityConfiguration : IEntityTypeConfiguration<StatusActivity>
    {
        public void Configure(EntityTypeBuilder<StatusActivity> entity)
        {
            entity.Property(e => e.ActivityId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.OriginalStatusCode).IsUnicode(false);

            entity.Property(e => e.StatusCode).IsUnicode(false);

            entity.HasOne(d => d.Agent)
                .WithMany(p => p.StatusActivities)
                .HasForeignKey(d => d.AgentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Status_Activity_Agent");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StatusActivity> entity);
    }
}
