// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ROWM.Dal;
using System;


namespace ROWM.Dal.Configurations
{
    public partial class StatusCategoryConfiguration : IEntityTypeConfiguration<StatusCategory>
    {
        public void Configure(EntityTypeBuilder<StatusCategory> entity)
        {
            entity.Property(e => e.CategoryCode).IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StatusCategory> entity);
    }
}
