// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Map", Schema = "App")]
    public partial class Map
    {
        [Key]
        [Column("ID")]
        public Guid Id { get; set; }
        public string Caption { get; set; }
        public int LayerType { get; set; }
        [StringLength(2048)]
        public string AgsUrl { get; set; }
        [StringLength(10)]
        public string LayerId { get; set; }
        public int DisplayOrder { get; set; }
        public int? ProjectPartId { get; set; }
        [Required]
        public bool? IsActive { get; set; }

        [ForeignKey(nameof(ProjectPartId))]
        [InverseProperty("Maps")]
        public virtual ProjectPart ProjectPart { get; set; }
    }
}