// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Cost_Estimate", Schema = "Austin")]
    public partial class CostEstimate
    {
        [Key]
        public Guid EstimateId { get; set; }
        [Required]
        [StringLength(40)]
        public string Line { get; set; }
        [Required]
        [Column("Design_Milestone")]
        [StringLength(10)]
        public string DesignMilestone { get; set; }
        [Column("TCAD_Prop_ID")]
        [StringLength(100)]
        public string TcadPropId { get; set; }
        [StringLength(100)]
        public string Segment { get; set; }
        [Column("Acquisition_Interest")]
        [StringLength(100)]
        public string AcquisitionInterest { get; set; }
        public int? Category { get; set; }
        [Column("Acq_Land_Cost")]
        public double? AcqLandCost { get; set; }
        [Column("Improvement_Cost")]
        public double? ImprovementCost { get; set; }
        public double? Damages { get; set; }
        [Column("OAS")]
        public double? Oas { get; set; }
        [Column("Total_Acquisition_Cost")]
        public double? TotalAcquisitionCost { get; set; }
        [Column("Total_ROW_Cost")]
        public double? TotalRowCost { get; set; }
        [Column("Appraised_Value")]
        public double? AppraisedValue { get; set; }
    }
}