// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Document_Title_Picklist", Schema = "Austin")]
    public partial class DocumentTitlePicklist
    {
        [Key]
        [Column("Title_Id")]
        public int TitleId { get; set; }
        [Required]
        [Column("Document_Type")]
        public string DocumentType { get; set; }
        [Required]
        [Column("Document_Title")]
        public string DocumentTitle { get; set; }
    }
}