// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Parcel_Relocation", Schema = "Austin")]
    public partial class ParcelRelocation
    {
        public ParcelRelocation()
        {
            RelocationCases = new HashSet<RelocationCase>();
        }

        [Key]
        public Guid ParcelRelocationId { get; set; }
        public Guid ParcelId { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset LastModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [InverseProperty(nameof(RelocationCase.ParentRelocation))]
        public virtual ICollection<RelocationCase> RelocationCases { get; set; }
    }
}