// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Relocation_Case", Schema = "Austin")]
    public partial class RelocationCase
    {
        public RelocationCase()
        {
            RelocationDisplaceeActivities = new HashSet<RelocationDisplaceeActivity>();
            RelocationEligibilities = new HashSet<RelocationEligibility>();
        }

        [Key]
        public Guid RelocationCaseId { get; set; }
        public Guid ParentRelocationId { get; set; }
        public Guid? AgentId { get; set; }
        public int RelocationNumber { get; set; }
        public int Status { get; set; }
        public int DisplaceeType { get; set; }
        public int RelocationType { get; set; }
        [StringLength(200)]
        public string DisplaceeName { get; set; }
        public Guid? ContactInfoId { get; set; }

        [ForeignKey(nameof(ParentRelocationId))]
        [InverseProperty(nameof(ParcelRelocation.RelocationCases))]
        public virtual ParcelRelocation ParentRelocation { get; set; }
        [InverseProperty(nameof(RelocationDisplaceeActivity.Case))]
        public virtual ICollection<RelocationDisplaceeActivity> RelocationDisplaceeActivities { get; set; }
        [InverseProperty(nameof(RelocationEligibility.Case))]
        public virtual ICollection<RelocationEligibility> RelocationEligibilities { get; set; }
    }
}