// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Relocation_Eligibility", Schema = "Austin")]
    public partial class RelocationEligibility
    {
        [Key]
        public Guid ActivityId { get; set; }
        public Guid CaseId { get; set; }
        public int OriginalStatus { get; set; }
        public int NewStatus { get; set; }
        public DateTimeOffset ActivityDate { get; set; }
        public Guid AgentId { get; set; }
        [StringLength(400)]
        public string Notes { get; set; }

        [ForeignKey(nameof(CaseId))]
        [InverseProperty(nameof(RelocationCase.RelocationEligibilities))]
        public virtual RelocationCase Case { get; set; }
    }
}