// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Relocation_Displacee_Activity", Schema = "Austin")]
    public partial class RelocationDisplaceeActivity
    {
        [Key]
        public Guid ActivityId { get; set; }
        public Guid CaseId { get; set; }
        [StringLength(20)]
        public string ActivityCode { get; set; }
        public int Activity { get; set; }
        public string ActivityDescription { get; set; }
        public Guid AgentId { get; set; }
        public DateTimeOffset ActivityDate { get; set; }
        public string Notes { get; set; }
        [Column(TypeName = "money")]
        public decimal? MoneyValue { get; set; }
        public bool? BooleanValue { get; set; }

        [ForeignKey(nameof(ActivityCode))]
        [InverseProperty(nameof(RelocationActivityType.RelocationDisplaceeActivities))]
        public virtual RelocationActivityType ActivityCodeNavigation { get; set; }
        [ForeignKey(nameof(CaseId))]
        [InverseProperty(nameof(RelocationCase.RelocationDisplaceeActivities))]
        public virtual RelocationCase Case { get; set; }
    }
}