// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ROWM.Dal
{
    [Table("Relocation_Activity_Type", Schema = "Austin")]
    public partial class RelocationActivityType
    {
        public RelocationActivityType()
        {
            RelocationDisplaceeActivities = new HashSet<RelocationDisplaceeActivity>();
        }

        [Key]
        [StringLength(20)]
        public string ActivityTypeCode { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool TrackSent { get; set; }
        public bool TrackDelivered { get; set; }
        public bool TrackSentConsultant { get; set; }
        public bool TrackSentClient { get; set; }
        public bool TrackClientApproval { get; set; }
        public bool IncludeYesNo { get; set; }
        public bool IncludeMoney { get; set; }

        [InverseProperty(nameof(RelocationDisplaceeActivity.ActivityCodeNavigation))]
        public virtual ICollection<RelocationDisplaceeActivity> RelocationDisplaceeActivities { get; set; }
    }
}