// <auto-generated />
namespace ROWM.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class supportsoftdelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(supportsoftdelete));
        
        string IMigrationMetadata.Id
        {
            get { return "202002090002188_support soft delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
