//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.hdr.Rowm.Export
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentLog
    {
        public string parcelid { get; set; }
        public string parcelstatuscode { get; set; }
        public string parcelstatus { get; set; }
        public string roestatuscode { get; set; }
        public string roestatus { get; set; }
        public string ownerfirstname { get; set; }
        public string ownerlastname { get; set; }
        public string agentname { get; set; }
        public System.DateTimeOffset dateadded { get; set; }
        public string contactchannel { get; set; }
        public string projectphase { get; set; }
        public string title { get; set; }
        public string notes { get; set; }
    }
}
