//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.hdr.Rowm.Export
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactList
    {
        public string parcelid { get; set; }
        public string partyname { get; set; }
        public int ownership_t { get; set; }
        public bool isprimarycontact { get; set; }
        public string ownerfirstname { get; set; }
        public string ownerlastname { get; set; }
        public string owneremail { get; set; }
        public string ownercellphone { get; set; }
        public string ownerhomephone { get; set; }
        public string ownerstreetaddress { get; set; }
        public string ownercity { get; set; }
        public string ownerstate { get; set; }
        public string ownerzip { get; set; }
        public string representation { get; set; }
    }
}
