//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.hdr.Rowm.Export
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentList
    {
        public string parcelid { get; set; }
        public string title { get; set; }
        public string contenttype { get; set; }
        public Nullable<System.DateTimeOffset> sentdate { get; set; }
        public Nullable<System.DateTimeOffset> delivereddate { get; set; }
        public string clienttrackingnumber { get; set; }
        public Nullable<System.DateTimeOffset> receiveddate { get; set; }
        public Nullable<System.DateTimeOffset> signeddate { get; set; }
        public string checkno { get; set; }
        public Nullable<System.DateTimeOffset> daterecorded { get; set; }
    }
}
